### ISSUE TITLE
Important Authorize.Net Networking Change

### ISSUE THREAD

**Issue by louisjpbacon** [joevandyk/authorize-net#8]
Hi there,

You probably already know this, but AR.net are changing to new Akamai transaction URLs that are available now and are:

```
https://api2.authorize.net/xml/v1/request.api
https://api2.authorize.net/soap/v1/Service.asmx
https://secure2.authorize.net/gateway/transact.dll
```

Will you be changing the transaction URL here:

https://github.com/joevandyk/authorize-net/blob/master/lib/authorize_net/xml_transaction.rb#L11

To the new api2 link?

Warm regards

Louis

**Comment by joevandyk** [comment]
This isn't an official repository. This is unmaintained. https://github.com/AuthorizeNet/sdk-ruby is the official one -- I would ask there.
